services:
  web:
    build: .
    container_name: flask_saas_web
    entrypoint: [ "/bin/bash", "/app/entrypoint.sh" ]
    volumes:
      - .:/app
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_CONFIG=development
      - APP_ENV=dev
      - DATABASE_URL=postgresql://neondb_owner:npg_eh3tK2PmidNA@ep-small-term-ahos6cxn-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - DB_HOST=ep-small-term-ahos6cxn-pooler.c-3.us-east-1.aws.neon.tech
      - DB_USER=neondb_owner
      - DB_NAME=neondb
      - POSTGRES_PASSWORD=npg_eh3tK2PmidNA
      - SECRET_KEY=dev-secret-key
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: postgres:15-alpine
    container_name: flask_saas_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flask_saas
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: flask_saas_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
